### ISSUE TITLE
Calculation of selected pages doesn't work properly

### ISSUE THREAD

**Issue by schulke-214** [schorfES/caroucssel#6]
This library fails to recognize the elements inside of `.scroller` right when `.scroller` is a css grid.
The padding on the right side doesnt work aswell. I think it might be related to the grid-gap.

Here is an example: https://www.moccu.com/about/ (pagination is broken on tablet and padding on the right side is broken on some screensizes aswell)

**Comment by schorfES** [comment]
Hi @schulke-214, thanks for contributing. Can you please specify the issue a bit more detailed. I never used it directly in a grid context. You're welcome to open a PR. ;-)

**Comment by schulke-214** [comment]
## Broken Pagination

due to the grid layout, the element recognition is failing from time to time.

![broken-pagination](https://user-images.githubusercontent.com/37018485/85137548-ad664300-b241-11ea-811a-c96d1d5294f9.png)

## Huge ::after

i still belive, that this is an issue with the grid-gap - i cant figure out how to calculate the right width for `::after`.

![huge-after-element](https://user-images.githubusercontent.com/37018485/85137562-b0f9ca00-b241-11ea-9c79-f748b8bc29fa.png)

**Comment by schorfES** [comment]
I guess it's more related to that items are mixed layout wise in the left to right order. I've created a prerelease that is combining all dots into "visual pages" (see #10). This PR is currently testable with the npm tag `caroucssel@next`. (Using this will bring some breaking changes to the current behaviour)

**Comment by schorfES** [comment]
@schulke-214, the feature for pages is now published to npm in version [0.6.0](https://github.com/schorfES/caroucssel/releases/tag/v0.6.0). Does the new behaviour solves your issues?

**Comment by schulke-214** [comment]
It seems like it's broken even more now:
![factcards](https://user-images.githubusercontent.com/37018485/87758602-0ad3bc80-c80d-11ea-89dd-7a1cc7793533.gif)

Did you test it with grids? I'll rebuild this kind of grid in a example repo - i dont actually know how to fix this without doing overly complex intersection observer things..

**Comment by schulke-214** [comment]
https://github.com/schulke-214/moccu-website-caroucssel-grid-example

It seems to work at least kind of. (The first pagination button never active - but spacings and other pagination stuff is working) So the problem is probably somewhere in the code for moccu.com.. 😄

**Comment by schorfES** [comment]
Ah okay, got it. This is related to how caroucssel calculates the visibility of pages. To not enable multiple pages at once it currently takes the last visible item and selects the corresponding page: https://github.com/schorfES/caroucssel/blob/master/src/index.js#L402

On your example page it will ever fail because the 5th element is already visible on startup. I'll need to take a deeper look into all the cases to find a "smarter" solution.

**Comment by schulke-214** [comment]
Maybe you already tried this out, maybe it's already more or less like this, or maybe this wont even work, but just a quick idea:

Does the pagination need to be so closely related to the pages? I know it sounds a little bit akward but if the pagination is just a interface for the scroll positions, it might solve issues like this.

e.g. if we have 4 pages and 4 pagination buttons, the buttons should'nt link to specfic items, they rather link to a scroll offset, like 0%, n%, 2n%, (100% - n%) (assuming one page is always 25% wide / n = 25)

I can try to implement a prototype if i find the time 🙂

**Comment by schorfES** [comment]
Hi @schulke-214, sorry for do not replying directly. 

The pagination more or less does this: [see here](https://github.com/schorfES/caroucssel/blob/master/src/index.js#L391). The issue is, that the carousel needs to handle all possible width of items. So items can sit in between two pages. As a user, you always want to scroll to a fully visible item. 

For example, if you scroll by pages exactly, there might be the case where the last 75% of an item will be visible and the first 25% of the following item. In this case, the user can not see any of the relevant content. To fix this, the carousel needs to scroll to the beginning of an item.

**Comment by schorfES** [comment]
@schulke-214 There is a new pre-release (version `0.7.0-0`) available which updates the calculation of pages and item visibility. It's available using `npm i caroucssel@next` or `yarn add caroucssel@next`.

**Comment by schorfES** [comment]
@schulke-214 There is a PR for your example: https://github.com/schulke-214/moccu-website-caroucssel-grid-example/pull/1

**Comment by schulke-214** [comment]
Thanks for solving this!
